# Generated by Django 5.2.5 on 2025-10-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('SUBSCRIBER', 'Subscriber')], default='SUBSCRIBER', max_length=15),
        ),
    ]
