# Generated by Django 5.2.5 on 2025-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tran_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
