# Generated by Django 5.2.5 on 2025-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
